### ISSUE TITLE
Plugins are not getting installed

### ISSUE THREAD

**Issue by ShubhamDingar** [PluginsOCSInventory-NG/security#2]
I tried to install the Security and cronTab plugin by downloading and putting their .zip file in /usr/share/ocsinventory-reports/ocsreports/download/. Then, when I go to my inventory and I try to install these plugins it shows an error message: "**ERROR: security is an invalid plugin, check your sources. Installation aborted !**".

I followed this link: https://github.com/PluginsOCSInventory-NG/security/releases
saying: 
1. Put security.zip in download folder in ocsreports ( By default /usr/share/ocsinventory-reports/ocsreports )
2. In the ocsreports webconsole click on plugins -> plugin manager
3. Select security in the dropdown and click on install.

Here's the screenshot of the error.
![screenshot from 2016-06-14 12 15 25](https://cloud.githubusercontent.com/assets/9039150/16033465/befcc932-3229-11e6-9719-474e5b8804ce.png)

**Comment by gillesdubois** [comment]
Hi,

you didn't downloaded the good file
Use this link instead : https://github.com/PluginsOCSInventory-NG/security/releases/download/1.0/security.zip

Regards,
Gilles Dubois.

**Comment by ShubhamDingar** [comment]
Thank you for the reply.

It is also giving the same error. 
**ERROR: security is an invalid plugin, check your sources.
Installation aborted !**

**Comment by vdeville** [comment]
Hello @shubhz14 
I have installed last release of security plugin and it's work perfectly.
Can you send me error log file of apache please ?
Thanks!

**Comment by ShubhamDingar** [comment]
This is what is says:
I have copied lines from /var/log/httpd/error_log

> [Tue Jun 14 12:32:20.047195 2016] [:error] [pid 804] [client 192.168.1.80:54688] PHP Warning:  mysqli_connect(): Headers and client library minor version mismatch. Headers:50535 Library:50631 in /usr/share/ocsinventory-reports/ocsreports/require/html_header.php on line 109, referer: http://192.168.1.205/ocsreports/?function=pluginsmanager
> [Tue Jun 14 12:32:20.047574 2016] [:error] [pid 804] [client 192.168.1.80:54688] PHP Warning:  mysqli_connect(): Headers and client library minor version mismatch. Headers:50535 Library:50631 in /usr/share/ocsinventory-reports/ocsreports/require/html_header.php on line 110, referer: http://192.168.1.205/ocsreports/?function=pluginsmanager
> [Tue Jun 14 12:32:20.053431 2016] [:error] [pid 804] [client 192.168.1.80:54688] PHP Warning:  ZipArchive::extractTo(): Permission denied in /usr/share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_plugins/functions_check.php on line 25, referer: http://192.168.1.205/ocsreports/?function=pluginsmanager
> [Tue Jun 14 12:32:20.560567 2016] [:error] [pid 804] [client 192.168.1.80:54688] PHP Warning:  mysqli_connect(): Headers and client library minor version mismatch. Headers:50535 Library:50631 in /usr/share/ocsinventory-reports/ocsreports/require/function_commun.php on line 150, referer: http://192.168.1.205/ocsreports/?function=pluginsmanager
> [Tue Jun 14 12:32:20.571598 2016] [:error] [pid 804] [client 192.168.1.80:54688] PHP Warning:  mysqli_connect(): Headers and client library minor version mismatch. Headers:50535 Library:50631 in /usr/share/ocsinventory-reports/ocsreports/require/function_commun.php on line 150, referer: http://192.168.1.205/ocsreports/?function=pluginsmanager
> [Tue Jun 14 12:32:20.576795 2016] [:error] [pid 804] [client 192.168.1.80:54688] PHP Warning:  ZipArchive::extractTo(): Permission denied in /usr/share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_plugins/functions_check.php on line 25, referer: http://192.168.1.205/ocsreports/?function=pluginsmanager
> [Tue Jun 14 12:54:45.406490 2016] [:error] [pid 821] [client 192.168.1.205:52753] PHP Warning:  mysqli_connect(): Headers and client library minor version mismatch. Headers:50535 Library:50631 in /usr/share/ocsinventory-reports/ocsreports/require/function_commun.php on line 150, referer: http://192.168.1.205/ocsreports/index.php?function=pluginsmanager
> [Tue Jun 14 12:54:45.423366 2016] [:error] [pid 821] [client 192.168.1.205:52753] PHP Warning:  mysqli_connect(): Headers and client library minor version mismatch. Headers:50535 Library:50631 in /usr/share/ocsinventory-reports/ocsreports/require/function_commun.php on line 150, referer: http://192.168.1.205/ocsreports/index.php?function=pluginsmanager
> [Tue Jun 14 12:54:45.443009 2016] [:error] [pid 821] [client 192.168.1.205:52753] PHP Warning:  mysqli_connect(): Headers and client library minor version mismatch. Headers:50535 Library:50631 in /usr/share/ocsinventory-reports/ocsreports/require/html_header.php on line 109, referer: http://192.168.1.205/ocsreports/index.php?function=pluginsmanager
> [Tue Jun 14 12:54:45.443756 2016] [:error] [pid 821] [client 192.168.1.205:52753] PHP Warning:  mysqli_connect(): Headers and client library minor version mismatch. Headers:50535 Library:50631 in /usr/share/ocsinventory-reports/ocsreports/require/html_header.php on line 110, referer: http://192.168.1.205/ocsreports/index.php?function=pluginsmanager
> [Tue Jun 14 12:54:45.454434 2016] [:error] [pid 821] [client 192.168.1.205:52753] PHP Warning:  ZipArchive::extractTo(): Permission denied in /usr/share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_plugins/functions_check.php on line 25, referer: http://192.168.1.205/ocsreports/index.php?function=pluginsmanager
> [Tue Jun 14 12:54:47.190777 2016] [:error] [pid 821] [client 192.168.1.205:52753] PHP Warning:  mysqli_connect(): Headers and client library minor version mismatch. Headers:50535 Library:50631 in /usr/share/ocsinventory-reports/ocsreports/require/function_commun.php on line 150, referer: http://192.168.1.205/ocsreports/index.php?function=pluginsmanager

**Comment by vdeville** [comment]
@shubhz14 
You don't have correct permissions on ocsreports.
`[Tue Jun 14 12:32:20.053431 2016] [:error] [pid 804] [client 192.168.1.80:54688] PHP Warning: ZipArchive::extractTo(): Permission denied in /usr/share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_plugins/functions_check.ph`
Give apache acces in write mode.
Thanks

**Comment by ShubhamDingar** [comment]
This are the permission given on ocsreports and also to all its subdirectories.

**drwxrwxrwx. 16 apache apache 4096 Jun 14 11:14 /usr/share/ocsinventory-reports/ocsreports**

**Comment by ShubhamDingar** [comment]
Now automatically security.zip and networkshare.zip have started working but crontab-master.zip is still showing errors. I am completely clueless about what just happened. 

Here's the screenshot:
![screenshot from 2016-06-14 15 12 04](https://cloud.githubusercontent.com/assets/9039150/16038503/cf92a474-3242-11e6-94fa-3381f3ab165f.png)

**Comment by vdeville** [comment]
For the moment crontab plugin is not released, please use only release for plugins.
Thanks.

**Comment by ShubhamDingar** [comment]
Thank you very much for you time. Two more things I wanted to ask from you.

1) How to activate the plugin from the client side? Like you have mentioned in you releases to Put vbs on Agents in order to retrieve their data.
Where to put the vbs file? Please tell me the path on client machine.

2) Is there any plugin that could retrieve the information about the removable devices like when were they connected, what data were transferred, etc,.?

Thank you.

**Comment by vdeville** [comment]
To activate plugin on client side place .vbs (windows) contain in "agent" folder of plugin root in "C:\Program Files (x86)\OCS Inventory Agent\Plugins" of windows client.

There is currently no plugin available which retrieve removable devices information. If you are brave you can do it ! 

Thank, Have good day.

**Comment by ShubhamDingar** [comment]
Thanks for your reply, okay I will work on developing that plugin.

I am a Linux user. Precisely, I work on Redhat Enterprise Linux 7 and CentOS 7. Please tell me the location for this distribution. Where to put .vbs file in Redhat Linux 7 agent.
Thank you.

**Comment by gillesdubois** [comment]
For linux you don't use a vbs file but a pm file.

To register a module on the linux agent you have to modify the modules.conf located in /etc/ocsinventory-agent/modules.conf (by default)

And put the modules in : /usr/local/share/perl/<PERLVERSION>/Ocsinventory/Agent/Modules (by default)

Regards,
Gilles Dubois.

**Comment by ShubhamDingar** [comment]
Okay, I have modified the modules.conf file for security located under /etc/ocsinventory-agent/
Ocsinventory::Agent::Modules::security;

But I didn't get what you have said next **And put the modules in : /usr/local/share/perl//Ocsinventory/Agent/Modules (by default)**

I don't have security.pm file, so how can I put the module in it?

**Comment by gillesdubois** [comment]
Security is not a plugin compatible with linux.
You will have to develop your proper pm file or wait for the new version.

Regards,
Gilles Dubois.

**Comment by ShubhamDingar** [comment]
So are there any plugins compatible for Linux? If yes, then please tell me from where to find them.

**Comment by vdeville** [comment]
Hello @shubhz14 
Crontabtask is unix plugin https://github.com/PluginsOCSInventory-NG/crontabTasks

Have nice day !

**Comment by PaveLGIL** [comment]
Hello!
I'm trying to install officepack plugin. But whet i try install i see this error "ERROR: officepack-master is an invalid plugin, check your sources. Installation aborted !".
Maybe can you help me?
![screen shot 2016-08-02 at 3 44 49 pm](https://cloud.githubusercontent.com/assets/15833990/17328861/937a8bee-58c8-11e6-94ab-541dd8722498.png)

**Comment by gillesdubois** [comment]
Hi,

You have to use the release files and not the download zip button from the github repository.
i.e : https://github.com/PluginsOCSInventory-NG/officepack/releases

Regards,
Gilles Dubois.

**Comment by PaveLGIL** [comment]
@gillesdubois Yes, it works! Thank you very much)

**Comment by enguerrandadeline** [comment]
Bonjour, j'ai aussi voulu installé le plugin Officepack toujours erreur MySQL error: Installation aborted !
Avez vous une solution ? Je suis sur une debian 9 avec Apache2 et php7 avec un OCS 2.0.

Hello, I also wanted to install the Officepack plugin always error MySQL error: Installation aborted!
Do you have a solution ? I am on a debian 9 with Apache2 and php7 with an OCS 2.0.


I'm sorry for my english I'm french.

**Comment by reginatuladhar** [comment]
Hello,

When I am trying to install plugin, I am getting following error:

"The communication server encountered the following error on install :  Err_02
Click here to solve your problem"

when I click on "Click here to solve your problem", it gives the following error

Here is the web service error code return :

Err_01 : Residual files found in plugins dir ( by default -> /etc/ocsinventory-server/plugins/PLUGIN_NAME.conf" )

Err_02 : Module transfer between ocsreports and ocsserver failed ( Can be a network related issue )

Err_03 : Can't write in plugins directory ( by default -> /etc/ocsinventory-server/plugins/" )

Err_04 : Can't write in perl directory ( by default -> /etc/ocsinventory-server/perl/Apache/Ocsinventory/Plugins )

Err_05 : Residual directory found in perl dir ( by default -> /etc/ocsinventory-server/perl/Apache/Ocsinventory/Plugins/PLUGIN_NAME/ )

Can anyone help me please?

Thank you
