### ISSUE TITLE
Security is empty

### ISSUE THREAD

**Issue by Scifire** [PluginsOCSInventory-NG/security#3]
Hey,

since update to OCS Server 2.3 (from 2.3RC) there is no data in the table  /Administrative data/Software/Security.
Also the mysql table securitycenter is empty.

We use Ubuntu 16.04 as Server with OCS 2.3 and Client Windows 10 Pro 64 Bit with Client 2.3.

**Comment by gillesdubois** [comment]
Hi, have you restarted your apache service after plugin install ? Can you check if there is a security folder and a security.conf file in the /etc/ocsinventory-server/ directory ? ( can be in a sub dir )

**Comment by Scifire** [comment]
uupps sorry... it seems that i forgot the restart. Today all data is shown. Thanks for hint :)

**Comment by gillesdubois** [comment]
No problems, have a nice day ! :)

Regards,
Gilles Dubois.
