### ISSUE TITLE
Plugins won´t work on Win2k8 R2

### ISSUE THREAD

**Issue by Scifire** [PluginsOCSInventory-NG/security#4]
Hey,
i´ve noticted that the vb scripts have no output on Windows Server 2008 R2, so OCS also gets no data from this.
Agentlog said also: `WARNING *** EXECUTABLE PLUGIN => Plugin <C:\Program Files (x86)\OCS Inventory Agent\plugins\security.vbs> does not produce any output`

Is this normal or just a missing dependency?

It´s a WIndows Server 2008 R2 SP1

**Comment by eliaspizarro** [comment]
same win10 redstone 2

**Comment by steph78630** [comment]
Hi @scifire91 and @eliaspizarro,

I will look at what I can do for this problem ... Who wants be beta-tester ?

I would also like to add additional security software recognition (eg: Spybot and others ...)> If you have any ideas ...

**Comment by Scifire** [comment]
@steph78630 thanks for that. But we don´t need this anymore. Currently i also have no time to do some testings, sorry.

**Comment by steph78630** [comment]
@scifire91 : No problem, thanks for the reply, bye !

**Comment by vdeville** [comment]
Hello,
I test on windows 10 and work waht is the error ?
@steph78630 i've time to test your version if you want
Thanks

**Comment by steph78630** [comment]
@MyValentinus Ok thanks, but it's not ready yet ... Later ?!

Harddrive and ipwan plugins are ready now ! Do you try install plugins please ?

**Comment by vdeville** [comment]
Yes send me email on: valentin@factorfx.com

**Comment by steph78630** [comment]
Ok, done
