### ISSUE TITLE
Unable to install plugin

### ISSUE THREAD

**Issue by grcmec** [PluginsOCSInventory-NG/security#8]
Hello,
I try to install the security plugin in the OCS Inventpry 2.4 over Centos 7.3, but when I try to install it I receive the followin error:

ERROR: security is an invalid plugin, check your sources.
Installation aborted !

The procedure that I follow was:

1. download the file from the ocs plugin site
2. Copy the securty.zip to /var/lib/ocsinventory-reports/plugins/download
3. chmod 777 security.zip
4. Plugins manager interface, I select the security from the dropdown and then clic in install booton.

I apreciate your help.

**Comment by steph78630** [comment]
Hi,

see the best answer at : http://ask.ocsinventory-ng.org/8747/scheduledtasks-plugins-not-visible?show=8762#a8762

Regards, Stéphane
